import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import HeaderButtons from "@/src/components/headerButtons";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center p-24">
          <div className="container mx-auto">
            <h2 className="text-2xl mb-2">
              Kevin Wang's ROR/React/Tailwind CSS Blog Example
            </h2>

            <HeaderButtons />

            <div className="mt-10">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
